spring:
  application:
    name: TheCommerce
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/thecommerce?useSSL=false&allowPublicKeyRetrieval=true
    #    username: "${username}"
    #    password: "${password}"
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  sql:
    init:
      mode: always
      schema-locations: classpath*:local/sql/schema.sql
      data-locations: classpath*:local/sql/data.sql
    output:
      ansi:
        enabled: always