DROP TABLE IF EXISTS User;

CREATE TABLE User (
    userid BIGINT PRIMARY KEY NOT NULL,
    password VARCHAR(100) NOT NULL,
    nickname VARCHAR(100) NOT NULL,
    username VARCHAR(100) NOT NULL,
    phonenumber VARCHAR(15) NOT NULL,
    email VARCHAR(50) NOT NULL
);